perfmark/perfmark

- api/src/main/java/io/perfmark/PerfMark.java
The original reason for this was to mirror the predecessor to PerfMark.  However,
the reason for this was to aid in the agent to rewrite the API calls, which
PerfMark doesn't depend on.
While it is good for these values to be constant, the annotation is not capable of
expressing other, useful types of constants (like Class.getName), and isn't
generally enforceable.  Instead, let this value be non-compile time constant,
but instead "runtime constant".  This term is intentionally vague, but roughly it
means that the cardinality of task and event names should scale with respect to the
amount of code, rather than the input size of the program.
> api: remove CompileTimeConstant

- api/src/main/java/io/perfmark/Impl.java
- api/src/main/java/io/perfmark/PerfMark.java
- impl/src/main/java/io/perfmark/impl/MarkHolder.java
- impl/src/main/java/io/perfmark/impl/NoopMarkHolderProvider.java
- impl/src/main/java/io/perfmark/impl/SecretPerfMarkImpl.java
- impl/src/main/java/io/perfmark/impl/Storage.java
- java6/src/jmh/java/io/perfmark/java6/SynchronizedMarkHolderBenchmark.java
- java6/src/main/java/io/perfmark/java6/SynchronizedMarkHolder.java
- java6/src/test/java/io/perfmark/java6/SynchronizedMarkHolderTest.java
- java9/src/jmh/java/io/perfmark/java9/VarHandleMarkHolderBenchmark.java
- java9/src/main/java/io/perfmark/java9/VarHandleMarkHolder.java
- java9/src/test/java/io/perfmark/java9/VarHandleMarkHolderTest.java
Sub tasks are meant for use when the task name is a concatenation of two, runtime constant
strings, but the caller doesn't want to pay the allocation cost.  None of these methods
support Tag overloads, and instead expect callers to invoke attachTag instead.
Perf:
```
Benchmark                                                  Mode  Cnt   Score   Error  Units
VarHandleGeneratorBenchmark.getAndSetAndGetGeneration      avgt    5   2.610 ± 0.022  ns/op
VarHandleGeneratorBenchmark.getGeneration                  avgt    5   2.379 ± 0.330  ns/op
VarHandleGeneratorBenchmark.racyGetAndSetAndGetGeneration  avgt    5  21.905 ± 2.327  ns/op
VarHandleMarkHolderBenchmark.event_name_noTag              avgt    5   3.581 ± 0.178  ns/op
VarHandleMarkHolderBenchmark.event_name_subname            avgt    5 …
```
> Add "subtask" variants of start, stop, and event

- WORKSPACE
- agent/src/main/java/io/perfmark/agent/PerfMarkTransformer.java
- build.gradle
Upgrade errorprone dependency to 2.3.4.
grpc-java complained perfmark's errorprone annotation 2.3.3: https://github.com/grpc/grpc-java/pull/6574/files#r361732377 .
```
compile (libraries.perfmark) {
exclude group: 'com.google.errorprone', module: 'error_prone_annotations'
}
```
If a perfmark release has newer version, grpc-java does not need to have the exclusion clause.
> Upgrade errorprone dependency to 2.3.4

- java9/build.gradle
- java9/src/test/java/io/perfmark/java9/VarHandleMarkHolderTest.java
We don't care about ErrorProne issues with jcstress's generated code.
VarHandleMarkHolderTest's warnings seem caused by checks that became obsolete
in f59adcfa.
Sampling of the fixed failures:
```
perfmark/java9/build/generated/sources/annotationProcessor/java/jcstress/org/openjdk/jcstress/infra/results/L_Result_jcstress.java:24: warning: [HidingField] Hiding fields of superclasses may cause confusion and errors. This field is hiding a field of the same name in superclass: L_Result_jcstress_c2
boolean p000, p001, p002, p003, p004, p005, p006, p007, p008, p009, p010, p011, p012, p013, p014, p015;
^
(see https://errorprone.info/bugpattern/HidingField)
perfmark/java9/src/test/java/io/perfmark/java9/VarHandleMarkHolderTest.java:201: warning: [ObjectToString] VarHandleMarkHolder is final and …
```
> Fix ErrorProne warnings

- .travis.yml
@carl-mastrangelo, if this seems fair to you, I'll enable travis-ci on this repository so you can see the build process. It takes ~2 minutes to run. We don't have to make the Travis status check required.
> Add Travis-CI build

- README.md
When I tried to use PerfMark and generate the html traces, I didn't have the proper trace library added. This just adds it to the README.
> Add perfmark-traceviewer to quickstart

- api/build.gradle
- api/src/main/java/io/perfmark/Impl.java
- api/src/main/java/io/perfmark/PerfMark.java
- api/src/main/java/io/perfmark/StringFunction.java
- api/src/test/java/io/perfmark/PerfMarkTest.java
- impl/src/main/java/io/perfmark/impl/SecretPerfMarkImpl.java
This allows delaying a tag being attached until later, in case the tag processing is expensive.    I only added it for tags, but a similar pattern can be used for events and tasks.   I gave myself some leeway with the implementation, but decided to be conservative with this PR.   Rather than stringifying the args on /reading/, it stringifies them on write.  I can't think of a clear way of expressing this distinction in the method name; ideas are welcome.  Stringing at write incurs a possible waste of work, but avoids synchronization and memory retention issues.   Stringing at read reduces the overhead of adding tags.
> api,impl: add a delayed tag impl

- api/src/jmh/java/io/perfmark/EnabledBenchmark.java
```
Benchmark                                     (enabled)  Mode  Cnt   Score   Error  Units
EnabledBenchmark.attachKeyedTag_sn                 true  avgt    5   7.275 ± 0.269  ns/op
EnabledBenchmark.attachKeyedTag_sn                false  avgt    5   0.605 ± 0.006  ns/op
EnabledBenchmark.attachKeyedTag_snn                true  avgt    5   8.585 ± 0.309  ns/op
EnabledBenchmark.attachKeyedTag_snn               false  avgt    5   0.631 ± 0.052  ns/op
EnabledBenchmark.attachKeyedTag_ss                 true  avgt    5   8.521 ± 0.315  ns/op
EnabledBenchmark.attachKeyedTag_ss                false  avgt    5   0.617 ± 0.009  ns/op
EnabledBenchmark.attachKeyedTag_ss_ctor            true  avgt    5  21.671 ± 0.276  ns/op
EnabledBenchmark.attachKeyedTag_ss_ctor           false  avgt    5   0.621 …
```
> api: add benchmarks for Lambda based tags

- api/src/jmh/java/io/perfmark/EnabledBenchmark.java
- api/src/main/java/io/perfmark/Impl.java
- api/src/main/java/io/perfmark/PerfMark.java
- api/src/test/java/io/perfmark/PerfMarkTest.java
- impl/src/main/java/io/perfmark/impl/SecretPerfMarkImpl.java
I decided to make string function failures still record, because otherwise it may cause task imbalances.
> all: add a method to start tasks with a string function

- agent/build.gradle
- api/build.gradle
- build.gradle
- impl/build.gradle
- java6/build.gradle
- java7/build.gradle
- java9/build.gradle
- java9/src/main/java/io/perfmark/java9/package-info.java
- java9/src/main/java/module-info.java
- traceviewer/build.gradle
- tracewriter/build.gradle
This makes Perfmark compatible with thew Java 9 Module system.   For classes compiled for 8 and lower, an `Automatic-Module-Name` field is added to the `MANIFEST.MF`, to ensure a stable module name.   (and not derive it from the jar name).   For the `java9` package, an actual module descriptor is added, which I have tested locally works.
> all: Add automatic module support

- .travis.yml
- build.gradle
JC stress is still not working with it yet, but the other fixes seem okay.
> all: update plugins to work with Gradle 7.0

- .github/workflows/gradle-wrapper-validation.yml
Reverts perfmark/perfmark#83
The `@2` already point to the latest version. This PR was cause by dependabot/dependabot-core#3194 and fixed by dependabot/dependabot-core#3708.
> Revert "build(deps): bump actions/checkout from 2 to 2.3.4"

- agent/src/main/java/io/perfmark/agent/PerfMarkTransformer.java
- agent/src/test/java/io/perfmark/agent/PerfMarkTransformerTest.java
ClassWriter has a bad habit of calling Class.forName, which forces class loading in the middle of instrumentation.    Refactor the Class Reading and writing to avoid this.
Additionally, try to be more lazy, preferring to return null to avoid VM work.
> agent: refactor agent to avoid classloading on start

- api/build.gradle
- api/src/main/java/io/perfmark/PerfMark.java
- api/src/test/java/io/perfmark/PerfMarkTest.java
The logging system in Java is pretty heavy weight, causing a lot of class loading to happen, Service Loaders, and Shutdown hooks.   It is expected that PerfMark is included in a lot
of places, but only occasionally accompanied by the implementation.    Avoid logging in the cases where the impl is absent. These were already FINE level logs usually, so they would
have been invisible in the common case.
Additionally, this also tries to avoid throwing an exception in the event a security manager is present.  Both Logger init and Boolean.getBoolean have Security Manager implications.
While the Secutiy is slated to go away in a later version of Java, it is still present in the versions PerfMark targets.
> api: avoid logging in static init.

- api/src/main/java/io/perfmark/PerfMark.java
- api/src/test/java/io/perfmark/PerfMarkTest.java
- impl/build.gradle
- impl/src/jmh/java/io/perfmark/impl/SecretPerfMarkImplClassInitBenchmark.java
- impl/src/main/java/io/perfmark/impl/SecretPerfMarkImpl.java
- impl/src/main/java/io/perfmark/impl/Storage.java
```
//Before
Benchmark                                                               Mode  Cnt      Score     Error        Units
SecretPerfMarkImplClassInitBenchmark.forName_init                         ss  400  17209.431 ± 354.263        us/op
SecretPerfMarkImplClassInitBenchmark.forName_init:·class.load             ss  400      3.599 ±   0.062  classes/sec
SecretPerfMarkImplClassInitBenchmark.forName_init:·class.load.norm        ss  400    152.523 ±   0.163   classes/op
SecretPerfMarkImplClassInitBenchmark.forName_init:·class.unload           ss  400        ≈ 0            classes/sec
SecretPerfMarkImplClassInitBenchmark.forName_init:·class.unload.norm      ss  400        ≈ 0             classes/op
SecretPerfMarkImplClassInitBenchmark.forName_noinit                       ss  400 …
```
> Avoid logging in common case.

- java9/build.gradle.kts
- java9/src/jmh/java/io/perfmark/java9/VarHandleGeneratorBenchmarkTest.java
- java9/src/jmh/java/io/perfmark/java9/VarHandleMarkHolderBenchmarkTest.java
- testing/src/main/java/io/perfmark/testing/GarbageCollector.java
- testing/src/main/java/io/perfmark/testing/MarkHolderBenchmark.java
Results:
```
Benchmark                                                                               (GC)  Mode  Cnt  Score   Error  Units
VarHandleMarkHolderBenchmarkTest.VarHandleMarkHolderBenchmark.event_name_noTag           CMS  avgt   10  3.506 ± 0.139  ns/op
VarHandleMarkHolderBenchmarkTest.VarHandleMarkHolderBenchmark.event_name_noTag       EPSILON  avgt   10  3.708 ± 0.156  ns/op
VarHandleMarkHolderBenchmarkTest.VarHandleMarkHolderBenchmark.event_name_noTag            G1  avgt   10  4.573 ± 0.241  ns/op
VarHandleMarkHolderBenchmarkTest.VarHandleMarkHolderBenchmark.event_name_noTag      PARALLEL  avgt   10  3.666 ± 0.021  ns/op
VarHandleMarkHolderBenchmarkTest.VarHandleMarkHolderBenchmark.event_name_noTag        SERIAL  avgt   10  3.724 ± 0.078  ns/op …
```
> java9: record benchmarks in permutation

- .github/workflows/gradle.yml
https://github.com/actions/setup-java/blob/main/README.md
```
NOTE: AdoptOpenJDK got moved to Eclipse Temurin and won't be updated anymore. It is highly recommended to migrate workflows from adopt to temurin to keep receiving software and security updates.
```
> ci: Temurin JDK

- api/build.gradle.kts
- api/src/main/java/io/perfmark/Impl.java
- api/src/main/java/io/perfmark/Tag.java
- api/src/main/java/io/perfmark/TaskCloseable.java
- api/src/main/java/io/perfmark/package-info.java
This removes javax.* types, which weren't ever really enforced. Primarily, Nullable was added, but the api surface is careful to not fail when null is provided, so it's not really needed.
> api: remove jsr305

- impl/src/main/java/io/perfmark/impl/SecretPerfMarkImpl.java
- impl/src/main/java/io/perfmark/impl/Storage.java
Tested with the Benchmark allowed to load the java7/9 packages
```
BEFORE
Benchmark                                             Mode  Cnt     Score     Error        Units
ClassInitBenchmark.forName_init                         ss  400  8730.958 ± 142.833        us/op
ClassInitBenchmark.forName_init:·class.load             ss  400     1.166 ±   0.015  classes/sec
ClassInitBenchmark.forName_init:·class.load.norm        ss  400    72.105 ±   0.112   classes/op
ClassInitBenchmark.forName_init:·class.unload           ss  400       ≈ 0            classes/sec
ClassInitBenchmark.forName_init:·class.unload.norm      ss  400       ≈ 0             classes/op
ClassInitBenchmark.forName_noinit                       ss  400  3040.308 ±  42.065        us/op
ClassInitBenchmark.forName_noinit:·class.load …
```
> impl: avoid loading noop classes

- build.gradle
This doesn't seem to provide as much benefit, but it does make loading more difficult if multiple copies are accidentally on the class path. Discovered while benchmarking.
> all: revert Sealed in Manifest

- api/testing/src/test/java/io/perfmark/apitesting/ArtifactTest.java
- impl/src/main/java/io/perfmark/impl/SecretPerfMarkImpl.java
```
BEFORE:
Benchmark                                             Mode  Cnt     Score     Error        Units
ClassInitBenchmark.forName_init                         ss  400  8411.036 ± 148.305        us/op
ClassInitBenchmark.forName_init:·class.load             ss  400     1.136 ±   0.016  classes/sec
ClassInitBenchmark.forName_init:·class.load.norm        ss  400    71.040 ±   0.113   classes/op
ClassInitBenchmark.forName_init:·class.unload           ss  400       ≈ 0            classes/sec
ClassInitBenchmark.forName_init:·class.unload.norm      ss  400       ≈ 0             classes/op
ClassInitBenchmark.forName_noinit                       ss  400  3077.689 ±  52.719        us/op
ClassInitBenchmark.forName_noinit:·class.load           ss  400     0.612 ±   0.007  classes/sec …
```
> impl: remove asserts causing classload
